First try to add a more detailed error message (see #543)
## Good

echo "(defn f [_] \n (/ 1 0)) \n  (require '[spartan.spec :as s])\n(s/explain (s/cat :x int? :y f) [1 #{:foo}]) nil" > working.bb

lein bb -f working.bb
java.lang.Exception: Could not require spartan.spec. [at /Users/jeroen/Projects/Github/babashka/working.bb, line 3, column 3]
     1: (defn f [_]
     2:  (/ 1 0))
     3:   (require '[spartan.spec :as s])
          ^--- Could not require spartan.spec. [at /Users/jeroen/Projects/Github/babashka/working.bb, line 3, column 3]
     4: (s/explain (s/cat :x int? :y f) [1 #{:foo}]) nil


## Bad

echo '(defn f [_] \n (/ 1 0)) \n  (/ a 2)\n(require '[spartan.spec :as s])\n(s/explain (s/cat :x int? :y f) [1 #{:foo}]) nil' > not_working.bb

lein bb -f test.bb
```
clojure.lang.ExceptionInfo: Could not resolve symbol: a [at line 3, column 6]
nil
Error encountered performing task 'run' with profile(s): 'test'
Suppressed exit
```